
version: '3'

services:
  mongo:
    image: mongo
    expose:
         - 27017
    ports:
         - "27017:27017"
  ginteil:
    image: ginteil/web
    expose:
      - 1337
    ports:
      - "1337:1337"
  individual:
    image: ginteil/individual
    deploy:
            mode: replicated
            replicas: 5
